[package]
name = "udp_playground"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bytes = "1.11.0"
rand = "0.9.2"
snow = "0.10.0"
tokio = { version = "1.48.0", features = ["full"] }
